name: terragrunt-snap
version: "0.44.5"
summary: A thin wrapper for Terraform 
license: MIT
contact: coty@fluidmind.dev
issues: https://github.com/coty91/terragrunt-snap/issues
source-code: https://github.com/coty91/terragrunt-snap
website: https://github.com/gruntwork-io/terragrunt
description: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
base: core22
grade: stable
confinement: classic
compression: lzo

apps:
  terragrunt:
    command: terragrunt

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

parts:
  terragrunt:
    plugin: go
    source: https://github.com/gruntwork-io/terragrunt
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w"
      cp terragrunt $SNAPCRAFT_PART_INSTALL/terragrunt
    stage:
      - terragrunt